name: Build and deploy React app to Azure Web App - TestBitryxReactApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload React build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A761E549FEAE4F1CA5A44C9DE7CBB553 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3CC251350EE14DA5A71D71B2E9CDB6EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DCDD335C954F47FC84197426DDDC85DC }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TestBitryxReactApp'
          slot-name: 'Production'
          package: .
